describe('Tugas 5 - Day 2 Sprint 5', function(){
    it('TC-Form', function(){
        cy.visit('https://demoqa.com/automation-practice-form')
        cy.get('#firstName').type('Ahmad').should('have.value','Ahmad')
        cy.get('#lastName').type('Saiful').should('have.value','Saiful')
        cy.get('#userEmail').type('ahmadsaifultest@gmail.com').should('have.value','ahmadsaifultest@gmail.com')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1)').click()
        cy.get('#userNumber').type('12345678').should('have.value','12345678')
        // cy.get('#dateOfBirthInput' , {force : true})
        //     .click().type('{selectall}' , '{backspace}').type('01 May 2000').type('{enter}')
        cy.get('#dateOfBirthInput').invoke('val','30 Dec 2000');
        cy.get('.subjects-auto-complete__value-container').type('Commerce{enter}')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3)').click()
        cy.get('input[type="file"]').attachFile('mdpl.jpg').should('be.visible')
        cy.get('#currentAddress').type('Kp. Suka Jadi').should('have.value','Kp. Suka Jadi')
        cy.get('#state > .css-yk16xz-control').type('Haryana{enter}')
        // cy.contains('#city > .css-yk16xz-control').should('disabled')
        cy.get('#submit').click()
    })
})
